# Generated by Django 4.1.6 on 2023-02-14 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards_app', '0002_rewardsshop_delete_cheapprize'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=10)),
                ('multiplyer', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
