# Generated by Django 4.1.6 on 2023-02-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_app', '0003_streakbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streakbadge',
            name='color',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
    ]
