# Generated by Django 4.1.6 on 2023-02-08 23:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0002_alter_daylogger_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DayLogger',
            new_name='Day',
        ),
    ]
