# Generated by Django 4.1.6 on 2023-02-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
