# Generated by Django 4.1.6 on 2023-02-09 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_updated',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
